config/routes.rb
Rails.application.routes.draw do
  resources :product2s
  resources :product2s
  resources :features
  resources :products

end

app/models/feature.rb
class Feature < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base

  serialize :feature , Array
end

app/models/product2.rb
class Product2 < ActiveRecord::Base
  belongs_to :feature
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :set_feature, only: [:show, :edit, :update, :destroy]

  # GET /features
  # GET /features.json
  def index
    @features = Feature.all
  end

  # GET /features/1
  # GET /features/1.json
  def show
  end

  # GET /features/new
  def new
    @feature = Feature.new
  end

  # GET /features/1/edit
  def edit
  end

  # POST /features
  # POST /features.json
  def create
    @feature = Feature.new(feature_params)

    respond_to do |format|
      if @feature.save
        format.html { redirect_to @feature, notice: 'Feature was successfully created.' }
        format.json { render :show, status: :created, location: @feature }
      else
        format.html { render :new }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /features/1
  # PATCH/PUT /features/1.json
  def update
    respond_to do |format|
      if @feature.update(feature_params)
        format.html { redirect_to @feature, notice: 'Feature was successfully updated.' }
        format.json { render :show, status: :ok, location: @feature }
      else
        format.html { render :edit }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature.destroy
    respond_to do |format|
      format.html { redirect_to features_url, notice: 'Feature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feature
      @feature = Feature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feature_params
      params.require(:feature).permit(:name, :sort, :active)
    end
end

app/controllers/product2s_controller.rb
class Product2sController < ApplicationController
  before_action :set_product2, only: [:show, :edit, :update, :destroy]

  # GET /product2s
  # GET /product2s.json
  def index
    @product2s = Product2.all
  end

  # GET /product2s/1
  # GET /product2s/1.json
  def show
  end

  # GET /product2s/new
  def new
    @product2 = Product2.new
  end

  # GET /product2s/1/edit
  def edit
  end

  # POST /product2s
  # POST /product2s.json
  def create
    @product2 = Product2.new(product2_params)

    respond_to do |format|
      if @product2.save
        format.html { redirect_to @product2, notice: 'Product2 was successfully created.' }
        format.json { render :show, status: :created, location: @product2 }
      else
        format.html { render :new }
        format.json { render json: @product2.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product2s/1
  # PATCH/PUT /product2s/1.json
  def update
    respond_to do |format|
      if @product2.update(product2_params)
        format.html { redirect_to @product2, notice: 'Product2 was successfully updated.' }
        format.json { render :show, status: :ok, location: @product2 }
      else
        format.html { render :edit }
        format.json { render json: @product2.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product2s/1
  # DELETE /product2s/1.json
  def destroy
    @product2.destroy
    respond_to do |format|
      format.html { redirect_to product2s_url, notice: 'Product2 was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product2
      @product2 = Product2.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product2_params
      params.require(:product2).permit(:name, :feature_id => [] )
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :feature => [] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/product2s_helper.rb
module Product2sHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/features/_form.html.erb
<%= simple_form_for(@feature) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :sort %>
    <%= f.input :active %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/features/edit.html.erb
<h1>Editing Feature</h1>

<%= render 'form' %>

<%= link_to 'Show', @feature %> |
<%= link_to 'Back', features_path %>

app/views/features/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Features</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sort</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @features.each do |feature| %>
      <tr>
        <td><%= feature.name %></td>
        <td><%= feature.sort %></td>
        <td><%= feature.active %></td>
        <td><%= link_to 'Show', feature %></td>
        <td><%= link_to 'Edit', edit_feature_path(feature) %></td>
        <td><%= link_to 'Destroy', feature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feature', new_feature_path %>

app/views/features/new.html.erb
<h1>New Feature</h1>

<%= render 'form' %>

<%= link_to 'Back', features_path %>

app/views/features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feature.name %>
</p>

<p>
  <strong>Sort:</strong>
  <%= @feature.sort %>
</p>

<p>
  <strong>Active:</strong>
  <%= @feature.active %>
</p>

<%= link_to 'Edit', edit_feature_path(@feature) %> |
<%= link_to 'Back', features_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rail299b</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/product2s/_form.html.erb
<%= simple_form_for(@product2) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
   
    <%= f.association :feature,
    :collection => @product2.feature.collect{ |p| [p.name, p.id] },
    :as => :check_boxes,
    :checked => params[:id]  %>
    
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>



<%# comment..============================================================== %>  
 
<% if false %>
block comment begins.. code to be commented out...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    <%= f.association :feature %>
 

ref.. 

http://stackoverflow.com/questions/5500923/how-to-preselect-an-association-checkbox-using-simple-form?rq=1
http://stackoverflow.com/questions/5500923/how-to-preselect-an-association-checkbox-using-simple-form?rq=1

http://stackoverflow.com/questions/13823655/rails-multiple-checkboxes-in-1-db-column-saves-correctly-but-doesnt-show-as-ch



end block comment    
<% end %>
   
<%# comment..============================================================== %>  
 

app/views/product2s/edit.html.erb
<h1>Editing Product2</h1>

<%= render 'form' %>

<%= link_to 'Show', @product2 %> |
<%= link_to 'Back', product2s_path %>

app/views/product2s/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Product2s</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Feature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product2s.each do |product2| %>
      <tr>
        <td><%= product2.name %></td>
        <td><%= product2.feature %></td>
        <td><%= link_to 'Show', product2 %></td>
        <td><%= link_to 'Edit', edit_product2_path(product2) %></td>
        <td><%= link_to 'Destroy', product2, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product2', new_product2_path %>

app/views/product2s/new.html.erb
<h1>New Product2</h1>

<%= render 'form' %>

<%= link_to 'Back', product2s_path %>

app/views/product2s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product2.name %>
</p>

<p>
  <strong>Feature:</strong>
  <%= @product2.feature %>
</p>

<%= link_to 'Edit', edit_product2_path(@product2) %> |
<%= link_to 'Back', product2s_path %>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
   <%= f.input :feature, as: :check_boxes, 
        collection:  ["ac", "StereoRadio", "4wheeldrive"], :checked => @product.feature %>

    <%= puts @product.feature %>
    <%= puts f.object.feature %>
        
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>


<%# comment..================================================================= %>  
 
<% if false %>
block comment begins.. code to be commented out..........................
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Prints to console from the puts statement I added above....
    ["StereoRadio", ""]

will not check the boxes after pressing edit...

    <%= f.input :feature, as: :check_boxes, 
        collection:  ["ac", "StereoRadio", "4wheeldrive"], :checked => @product.feature %>

        
this will check the StereoRadio box...

    <%= f.input :feature, as: :check_boxes, 
        collection:  ["ac", "StereoRadio", "4wheeldrive"], :checked => ["StereoRadio", ""] %>

        
ref.. 
  = f.input :features, as: :check_boxes, 
    collection:  ["ac", "Stereo Radio", "4 wheel drive"], :checked => f.object.feature.to_s
 
orig.. 
     <%= f.input :feature %> 

ref.. 

http://stackoverflow.com/questions/13823655/rails-multiple-checkboxes-in-1-db-column-saves-correctly-but-doesnt-show-as-ch

http://stackoverflow.com/questions/5500923/how-to-preselect-an-association-checkbox-using-simple-form?rq=1

  
simple_form checkboxes save to database column as array but will not retrieve from database and re-check boxes on edit

simple_form pre-check check_boxes from database on edit


f.input :my_boolean, input_html: { checked: @object.my_boolean }



end block comment    
<% end %>
   
<%# comment..================================================================= %>  
 

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Feature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.feature %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Feature:</strong>
  <%= @product.feature %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>